# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 036d061790344ab533a076370aedc370ce42ca672f5c11ef1cba6e659f27e8fc1ebb56e2ea9ad7eea5ddc49f5d2986bf4ce8795e2786c9ab0e005a9279c62777

test:
  secret_key_base: fb826e13054e47a1c1b55ab72ae498ccbecee74602d92447e5aa9c71e748d1da8c683d3211b4a7a272032b82951354de4cc7876562a37199a99d62a6a38c2a14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
